# Generated by Django 6.1 on 2026-08-27 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Maintenance Staff'), ('ADMIN', 'Administrator')], default='STUDENT', help_text='Role-Based Access Control level', max_length=10)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for communication', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when profile was created')),
                ('user', models.OneToOneField(help_text='Underlying Django auth user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
