# Generated by Django 6.1 on 2026-08-27 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the complaint category', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Scope and description of this maintenance category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for new complaint submissions')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, help_text='Unique auto-generated ticket identifier (e.g., CMP-000123)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Short summary of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the breakdown or maintenance required')),
                ('location', models.CharField(help_text='Exact physical location (e.g., Block B, Room 302, Library 1st Floor)', max_length=255)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Urgency level of the complaint', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', help_text='Current state in the complaint lifecycle', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional photo of the damaged facility or equipment', null=True, upload_to='complaints/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when complaint was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when complaint was last updated')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when staff marked the issue resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when student/admin closed the ticket', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Maintenance staff member assigned to fix the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Maintenance department/category', on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.category')),
                ('submitted_by', models.ForeignKey(help_text='Student who created and reported the complaint', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], help_text='Status before transition', max_length=20)),
                ('new_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], help_text='Status after transition', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Action notes or required resolution explanation', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Exact timestamp of the status transition')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who initiated this status transition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(help_text='Parent complaint ticket', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint History',
                'verbose_name_plural': 'Complaint Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
